Fruitables/Fruitables/Models/Tag.cs
namespace Fruitables.Models
{
    public class Tag : BaseEntity
    {
        public string Name { get; set; }
        public ICollection<ProductTag> ProductTags { get; set; }

    }
}

Fruitables/Fruitables/Areas/Admin/Controllers/CategoryController.cs
using Fruitables.Data;
using Fruitables.Areas.Admin.ViewModels.CategoryVM;
using Fruitables.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fruitables.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> categories = await _context.Categories.ToListAsync();
            IEnumerable<GetAllCategoryVM> getAllCategoryVMs = categories.Select(c => new GetAllCategoryVM()
            {
                Id = c.Id,
                Name = c.Name
            });

            return View(getAllCategoryVMs);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryVM categoryVM)
        {
            if (!ModelState.IsValid) return View(categoryVM);

            var dbName = await _context.Categories.FirstOrDefaultAsync(m => m.Id == 6);

            if (dbName != null)
            {
                string ctName = dbName.Name.ToLower().Trim();
            }

            string newName = categoryVM.Name.ToLower().Trim();

            bool isExist = await _context.Categories.AnyAsync(c => c.Name.ToUpper().Trim() ==
                                                         categoryVM.Name.ToUpper().Trim());

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu adda movcuddur!");
                return View(categoryVM);
            }

            Category category = new Category
            {
                Name = categoryVM.Name.Trim()
            };

            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            Category category = await _context.Categories
                .FirstOrDefaultAsync(c => c.Id == id);

            if (category == null)
                return NotFound();

            DetailCategoryVM detailCategoryVM = new()
            {
                Id = category.Id,
                Name = category.Name
            };

            return View(detailCategoryVM);
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            Category category = await _context.Categories
                .FirstOrDefaultAsync(c => c.Id == id);

            if (category == null)
                return NotFound();

            UpdateCategoryVM updateCategoryVM = new()
            {
                Id = category.Id,
                Name = category.Name
            };

            return View(updateCategoryVM);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateCategoryVM request)
        {
            if (!ModelState.IsValid)
                return View(request);

            Category category = await _context.Categories
                .FirstOrDefaultAsync(c => c.Id == id);

            if (category == null)
                return NotFound();

            bool isExist = await _context.Categories.AnyAsync(c =>
                c.Name.Trim().ToLower() == request.Name.Trim().ToLower()
                && c.Id != id);

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu adda movcuddur!");
                return View(request);
            }

            category.Name = request.Name.Trim();

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _context.Categories.FirstOrDefaultAsync(c => c.Id == id);
            if (category == null) return NotFound();

            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Fruitables/Fruitables/Areas/Admin/Controllers/TagController.cs
using Fruitables.Areas.Admin.ViewModels.TagVM;
using Fruitables.Data;
using Fruitables.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fruitables.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var tags = await _context.Tags
                .Select(t => new GetAllTagVM
                {
                    Id = t.Id,
                    Name = t.Name
                })
                .ToListAsync();

            return View(tags);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTagVM request)
        {
            if (!ModelState.IsValid)
                return View(request);

            bool isExist = await _context.Tags.AnyAsync(t =>
                t.Name.Trim().ToLower() == request.Name.Trim().ToLower());

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu adda tag movcuddur!");
                return View(request);
            }

            Tag tag = new()
            {
                Name = request.Name.Trim()
            };

            await _context.Tags.AddAsync(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
            if (tag == null) return NotFound();

            DetailTagVM vm = new()
            {
                Id = tag.Id,
                Name = tag.Name
            };

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
            if (tag == null) return NotFound();

            UpdateTagVM vm = new()
            {
                Id = tag.Id,
                Name = tag.Name
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateTagVM request)
        {
            if (id != request.Id) return BadRequest();

            if (!ModelState.IsValid)
                return View(request);

            var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
            if (tag == null) return NotFound();

            bool isExist = await _context.Tags.AnyAsync(t =>
                t.Name.Trim().ToLower() == request.Name.Trim().ToLower()
                && t.Id != id);

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu adda tag movcuddur!");
                return View(request);
            }

            tag.Name = request.Name.Trim();
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
            if (tag == null) return NotFound();

            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Fruitables/Fruitables/Areas/Admin/Views/Tag/Create.cshtml
@using Fruitables.Areas.Admin.ViewModels.TagVM
@model CreateTagVM

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Tag</h4>

            <form asp-area="Admin" asp-controller="Tag" asp-action="Create" method="post">
                <div class="form-group">
                    <label asp-for="Name">Tag Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Tag adı daxil edin" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-success btn-rounded btn-fw">
                    Save
                </button>

                <a asp-area="Admin" asp-controller="Category" asp-action="Index"
                   class="btn btn-secondary btn-rounded btn-fw">
                    Back
                </a>
            </form>
        </div>
    </div>
</div>

Fruitables/Fruitables/Areas/Admin/Views/Tag/Detail.cshtml
@using Fruitables.Areas.Admin.ViewModels.TagVM
@model DetailTagVM

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Tag Detail</h4>

            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <tr>
                        <th>Id</th>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>@Model.Name</td>
                    </tr>
                </table>
            </div>

            <a asp-action="Index" class="btn btn-secondary mt-3">
                <i class="mdi mdi-arrow-left"></i> Back
            </a>
        </div>
    </div>
</div>

Fruitables/Fruitables/Areas/Admin/Views/Tag/Index.cshtml
@using Fruitables.Areas.Admin.ViewModels.TagVM
@model IEnumerable<GetAllTagVM>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Tag</h4>
            <a class="btn btn-success btn-rounded btn-fw" asp-controller="Tag" asp-action="Create">
                <i class="mdi mdi-library-plus"></i>
            </a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Settings</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>

                                <td>
                                    <a class="btn btn-info btn-rounded btn-fw" asp-controller="Tag" asp-action="Detail" asp-route-id="@item.Id"><i class="mdi mdi-alert-circle-outline"></i></a>
                                    <a class="btn btn-primary btn-rounded btn-fw" asp-controller="Tag" asp-action="Update" asp-route-id="@item.Id"><i class="mdi mdi-border-color"></i></a>
                                    <form asp-action="Delete"
                                          asp-route-id="@item.Id"
                                          method="post"
                                          class="d-inline">

                                        <button type="submit"
                                                class="btn btn-danger btn-rounded btn-fw"
                                                title="Sil">
                                            <i class="mdi mdi-delete"></i>
                                        </button>

                                    </form>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Fruitables/Fruitables/Areas/Admin/Views/Tag/Update.cshtml
@using Fruitables.Areas.Admin.ViewModels.TagVM
@model UpdateTagVM

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Tag</h4>

            <form asp-action="Update" method="post">

                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="mdi mdi-content-save"></i> Update
                </button>

                <a asp-action="Index" class="btn btn-secondary ml-2">
                    <i class="mdi mdi-arrow-left"></i> Back
                </a>
            </form>
        </div>
    </div>
</div>